FROM ubuntu:latest
RUN apt-get update && apt-get install -y python3 python3-pip build-essential libssl-dev libffi-dev python3-dev
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY . .
CMD ["python3", "app.py"]